// Copyright 2024-2026 Reflective Labs
// SPDX-License-Identifier: MIT

//! Streaming chat — an additive extension over `ChatBackend`.
//!
//! `ChatBackend::chat(req)` returns the entire response after the model is
//! done generating. For UI use cases (real-time token rendering, mid-stream
//! tool-call dispatch, long reasoning traces) you want events as they arrive.
//!
//! `StreamingChatBackend` adds a single `chat_stream(req)` method that
//! returns a `Stream` of `ChatEvent` values. Implementations parse the
//! provider's wire format (typically SSE) and emit one event per delta.
//!
//! # Status
//!
//! This is a **manifold-local** trait — it doesn't (yet) live in
//! `converge_provider`. Once enough backends implement it and the event
//! shape is proven, the trait + types are candidates for upstreaming.
//!
//! # Usage
//!
//! ```ignore
//! use futures::StreamExt;
//! use manifold::llm::{ChatEvent, OpenRouterBackend, StreamingChatBackend};
//!
//! let backend = OpenRouterBackend::from_env()?;
//! let mut stream = backend.chat_stream(request).await?;
//! while let Some(event) = stream.next().await {
//!     match event? {
//!         ChatEvent::TextDelta(s) => print!("{s}"),
//!         ChatEvent::Finish(reason) => println!("\n[finish: {reason:?}]"),
//!         _ => {}
//!     }
//! }
//! ```

use std::pin::Pin;

use converge_provider::{ChatBackend, ChatRequest, FinishReason, LlmError, TokenUsage};
use futures::Stream;

/// One event from a streaming chat response.
#[derive(Debug, Clone)]
pub enum ChatEvent {
    /// Incremental text generated by the model. Concatenate all `TextDelta`
    /// payloads in order to reconstruct the final response content.
    TextDelta(String),
    /// A new tool call has begun. Subsequent `ToolCallArgsDelta` events with
    /// the same `index` (or `id`) belong to this call.
    ToolCallStart {
        id: String,
        name: String,
        index: u32,
    },
    /// Incremental serialized arguments for a tool call (typically streamed
    /// JSON). Concatenate all deltas for one tool call to get the full args.
    ToolCallArgsDelta {
        id: String,
        index: u32,
        args_delta: String,
    },
    /// The model finished generating with the given reason. Streams should
    /// emit `Finish` once before terminating.
    Finish(FinishReason),
    /// Final token usage. Emitted at most once, near the end of the stream.
    Usage(TokenUsage),
}

/// A boxed, pinned stream of `ChatEvent` values. Errors terminate the stream
/// (the stream yields `Err` then ends).
pub type ChatStream<'a> = Pin<Box<dyn Stream<Item = Result<ChatEvent, LlmError>> + Send + 'a>>;

/// A `ChatBackend` that also supports SSE-style streaming responses.
///
/// Implementations should:
/// - Open the upstream POST with `"stream": true` in the request body.
/// - Parse `text/event-stream` deltas as they arrive.
/// - Emit one `ChatEvent` per delta — `TextDelta` for content, plus the
///   tool-call events when the model invokes a tool.
/// - Emit exactly one `Finish` event (with `FinishReason::Stop`,
///   `Length`, `ToolCalls`, etc.) before the stream terminates.
/// - Optionally emit one `Usage` event when the upstream reports it
///   (OpenAI/OpenRouter include usage in the final delta when
///   `stream_options.include_usage` is set).
pub trait StreamingChatBackend: ChatBackend {
    /// Begin a streaming chat call. The future resolves once the connection
    /// is open and the response headers are received; the stream then yields
    /// events as they arrive.
    fn chat_stream(
        &self,
        req: ChatRequest,
    ) -> Pin<Box<dyn std::future::Future<Output = Result<ChatStream<'_>, LlmError>> + Send + '_>>;
}
